language: c
os:
  - linux
sudo: false
envs:
  global:
    - CONDA_DEPENDENCIES=constructor
    - PYTHON_VERSION=3.8
    - VERSION=1.2.0
    - CUDA_VERSION=10.1
matrix:
  include:
    - env:
      - NAME="deepmd-kit-cpu"
      - NAME="deepmd-kit-gpu"
install:
  - git clone --depth 1 git://github.com/astropy/ci-helpers.git
  - source ci-helpers/travis/setup_conda.sh
script:
  - constructor $NAME
before_deploy:
  - git config --local user.name "njzjz"
  - git config --local user.email "jinzhe.zeng@rutgers.edu"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: deepmd-kit-*.sh
  skip_cleanup: true
  file_glob: true
  on:
    repo: deepmd-kit-recipes/installer
    branch: master
    tags: true
